### ISSUE TITLE
Windows Issues

### ISSUE THREAD

**Issue by lymarrie** [yext/pages#160]
### Describe the bug

Hi,

The build seems to fail on Windows machines. I used node version 17.9.1.
I run into the following error after running `yext pages generate`

```
Warning: CI execution for this site will be in Linux - please be sure your build commands are 
compatible in that environment
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead. 
✖ [13ms] Nothing to clean
✖ [10ms] Failed to copy Yext plugin files
✔ [27ms] Successfully copied Yext plugin files
✔ [60ms] Generated 2 hydration entry-points
✔ [3ms] Injected template renderer.
✓ 15 modules transformed.
✔ [4ms] Validated template modules
✔ [5ms] Successfully wrote C:\Users\[name]\react\pages-starter-react-locations\sites-config
✖ [2ms] Failed to write manifest.json
ENOENT: no such file or directory, open 'C:\Users\[name]\react\pages-starter-react-locations\dist/plugin/manifest.json'
[vite]: Rollup failed to resolve import "....src        emplateslocation" from "dist/hydration_templates/location.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "....src emplateslocation" from "dist/hydration_templates/location.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///C:/Users/[name]/react/pages-starter-react-locations/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:43609:19)
    at onwarn (file:///C:/Users/[name]/react/pages-starter-react-locations/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:43399:13)
    at Object.onwarn (file:///C:/Users/[name]/react/pages-starter-react-locations/node_modules/rollup/dist/es/shared/rollup.js:23178:13)
    at ModuleLoader.handleResolveId (file:///C:/Users/[name]/react/pages-starter-react-locations/node_modules/rollup/dist/es/shared/rollup.js:22335:26)
    at file:///C:/Users/[name]/react/pages-starter-react-locations/node_modules/rollup/dist/es/shared/rollup.js:22296:26
```

### System Info

```shell
Microsoft Windows 10 Pro, x64-based PC, node version 17.9.1, npm version 8.11.0, deno 1.24.2 (release, x86_64-pc-windows-msvc), typescript 4.7.4
```

### Used Package Manager

npm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by lambdaFun94** [comment]
@mkilpatrick Was looking for a status update on this
