### ISSUE TITLE
`pages generate features` fails with confusing error

### ISSUE THREAD

**Issue by bhainesva** [yext/pages#182]
### Describe the bug

I tried updating https://github.com/yext/pages-starter-react-locations to 1.0.0-beta.2 and adding a package.json script to run `pages generate features`. 

![image](https://user-images.githubusercontent.com/6308571/186525511-7cc88b16-6f9f-4e89-b146-8ac1e76b4966.png)

When I try running the command I get an error that looks like it's coming from pagesjs:
```
bhaines@bhaines-mbp pages-starter-react-locations % yarn features
yarn run v1.22.18
$ pages generate features
/Users/bhaines/repo/pages-starter-react-locations/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Could not import /Users/bhaines/repo/pages-starter-react-locations/src/templates/static.tsx TypeError: Cannot read properties of undefined (reading 'bind')
    at loadTemplateModules (file:///Users/bhaines/repo/pages-starter-react-locations/node_modules/@yext/pages/dist/common/src/template/internal/loader.js:27:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async features (file:///Users/bhaines/repo/pages-starter-react-locations/node_modules/@yext/pages/dist/generate/features.js:12:27)
    at async file:///Users/bhaines/repo/pages-starter-react-locations/node_modules/@yext/pages/dist/bin/pages.js:47:9

Node.js v17.4.0
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 510.91 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v17.4.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 103.0.2
    Safari: 15.4
  npmPackages:
    @yext/pages: ^1.0.0-beta.2 => 1.0.0-beta.2
```

### Used Package Manager

yarn

### Used Browser

Firefox

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
This is an [issue](https://github.com/lucasfeliciano/fetch-everywhere/issues/9) with fetch-everywhere. Swap to the provided fetch util in this repo.
