### ISSUE TITLE
default export should not be required in templates

### ISSUE THREAD

**Issue by tatimblin** [yext/pages#218]
### Describe the bug

I am trying to add a robots.txt to a site following [this guide](https://hitchhikers.yext.com/docs/pages/robots.txt/). If I paste the sample into my project, build the site, and then try and serve I get an error that the template is missing a default export.

```
Error: Default export missing in template: /src/templates/robots.ts
```

~~I am, able to get around this issue by adding a default export like so~~ Doing this just uses the html wrappers and turns the should be txt file into an html file.

```
export default render;
```

For more context, I am not able to have the default export be any of the following i.e.

```
export default undefined;

export default {};

export default () => {};
```

It must be a function that returns a string, and that string will take precedence over the render function.

### Reproduction

https://github.com/yext-pages/Master-Ria

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 681.34 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.4.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.0 - ~/repo/Master-Ria/node_modules/.bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Firefox: 100.0
    Safari: 15.6.1
  npmPackages:
    @yext/pages: 1.0.0-beta.6 => 1.0.0-beta.6
```

### Used Package Manager

pnpm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by bhainesva** [comment]
I'm still seeing this issue trying to add a robots.txt file on beta-9. For example here: https://github.com/yextconsulting/site-starter-react-consulting.

It works when running `yarn dev`, but `yarn build` gives me this:
```
'default' is not exported by src/templates/robots.tsx, imported by dist/hydration_templates/robots.tsx
file: /Users/bhaines/repo/site-starter-react-basic/dist/hydration_templates/robots.tsx:3:7
1: import * as React from "react";
2: import * as ReactDOM from "react-dom";
3: import Page from "../../src/templates/robots";
          ^
4: 
5: const data = (window as any).__INITIAL__DATA__;
error during build:
Error: 'default' is not exported by src/templates/robots.tsx, imported by dist/hydration_templates/robots.tsx
    at error (file:///Users/bhaines/repo/site-starter-react-basic/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///Users/bhaines/repo/site-starter-react-basic/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
    at Module.traceVariable (file:///Users/bhaines/repo/site-starter-react-basic/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
    at ModuleScope.findVariable (file:///Users/bhaines/repo/site-starter-react-basic/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
    at Identifier.bind (file:///Users/bhaines/repo/site-starter-react-basic/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:7439:40)
    at CallExpression.bind (file:///Users/bhaines/repo/site-starter-react-basic/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5265:73)
    at CallExpression.bind (file:///Users/bhaines/repo/site-starter-react-basic/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:8935:15)
    at CallExpression.bind (file:///Users/bhaines/repo/site-starter-react-basic/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5265:73)
    at CallExpression.bind (file:///Users/bhaines/repo/site-starter-react-basic/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:8935:15)
    at ExpressionStatement.bind (file:///Users/bhaines/repo/site-starter-react-basic/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
error Command failed with exit code 1.

```

**Comment by bhainesva** [comment]
Ok so if I export the render function, and also do `export default render` it works. If I don't do the named export it uses the full html template instead of giving me full control, if I don't do the default export it gives me that error. 

Going to reopen this, but feel free to split into a different thing if that works better for yall.

**Comment by jwartofsky-yext** [comment]
Is this issue still occurring?

I was able to use each of these in robots.ts on the [starter-repo](https://github.com/yext/pages-starter-react-locations) without it causing an error.

no default export

export default undefined;

export default {};

export default () => {};

Tested using 1.0.0-beta.21 with `npm run prod` and `npm run build:serve`

Also tested with 1.0.0-rc.5 with `npm run prod` and `npm run dev`

**Comment by jwartofsky-yext** [comment]
This appears to be fixed.

If I run dev or prod with this [robots.ts](https://github.com/yextconsulting/pages-starter-react-consulting/blob/main/src/templates/robots.ts), it works without issue.

If I have no render function and no default export (or export default undefined), I get
`Module robots.js does not have the necessary exports to produce page. A module should either have a React component as a default export or a render function.`

The [robots.ts](https://github.com/yext/pages-starter-react-locations/blob/main/src/templates/robots.ts) in the starter-repo also works without error or a default export.
